import React from 'react';
import { ChevronLeft } from 'lucide-react';

interface Props { onBack: () => void; }

const sections = [
  {
    title: '1. Information We Collect',
    body: 'We collect your Telegram profile data (ID, first name, username) when you authenticate via Telegram. For KYC verification we collect full name, date of birth, country, government-issued ID number, BVN or NIN, and a selfie/liveness check. Financial data (transaction history, wallet balances, virtual card usage) is generated by your use of the app.',
  },
  {
    title: '2. How We Use Your Data',
    body: 'Your data is used exclusively to operate BorderPay: authenticating you, maintaining your wallet, processing transfers, issuing virtual cards, and complying with Nigerian financial regulations (CBN, FCCPC). We do not sell, share, or use your data for advertising.',
  },
  {
    title: '3. Data Storage & Security',
    body: 'All data is stored in encrypted PostgreSQL databases. Sensitive values (BVN, NIN, card tokens) are encrypted at rest using AES-256-GCM before storage. Connections are encrypted via TLS 1.3. Access is restricted to authenticated staff only.',
  },
  {
    title: '4. Data Retention',
    body: 'Transaction records are retained for 7 years to comply with AML/CFT regulations. Account data is retained for as long as your account is active. You may request deletion of non-regulated data by contacting support.',
  },
  {
    title: '5. Third-Party Services',
    body: 'BorderPay integrates with Sudo Africa (card issuance), PayPoint (virtual accounts), and Telegram (authentication). Each provider has their own privacy policy. We share only the minimum data required for each service to function.',
  },
  {
    title: '6. Your Rights',
    body: 'You have the right to access your personal data, correct inaccuracies, and request deletion of non-regulated data. Contact our support team via Telegram or email to exercise these rights.',
  },
  {
    title: '7. Contact',
    body: 'For privacy enquiries, contact us at support@borderpay.app or via our Telegram support channel. We respond within 2 business days.',
  },
];

export default function PrivacyPolicyPage({ onBack }: Props) {
  return (
    <div className="page" style={{ paddingTop: '16px', paddingBottom: '40px' }}>
      <button onClick={onBack} style={{ display: 'flex', alignItems: 'center', gap: '6px', background: 'none', border: 'none', color: 'var(--accent)', fontSize: '14px', cursor: 'pointer', marginBottom: '20px', padding: 0, fontFamily: 'inherit', fontWeight: 700 }}>
        <ChevronLeft size={18} /> Back
      </button>

      <div style={{ marginBottom: '24px' }}>
        <h2 style={{ fontSize: '22px', fontWeight: 900, marginBottom: '4px' }}>Privacy Policy</h2>
        <p style={{ fontSize: '12px', color: 'var(--text-muted)' }}>Last updated: July 2026 · BorderPay v1.0</p>
      </div>

      <div style={{ padding: '14px 16px', background: 'rgba(108,92,231,0.07)', borderRadius: '14px', border: '1px solid rgba(108,92,231,0.18)', marginBottom: '20px' }}>
        <p style={{ fontSize: '13px', color: 'var(--purple)', fontWeight: 600, lineHeight: 1.5 }}>
          BorderPay is committed to protecting your privacy and complying with the Nigeria Data Protection Act (NDPA) 2023 and CBN regulations.
        </p>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
        {sections.map(s => (
          <div key={s.title} style={{ background: 'var(--surface)', borderRadius: '16px', padding: '18px', boxShadow: 'var(--shadow-sm)' }}>
            <p style={{ fontSize: '14px', fontWeight: 800, marginBottom: '8px', color: 'var(--text)' }}>{s.title}</p>
            <p style={{ fontSize: '13px', color: 'var(--text-muted)', lineHeight: 1.6 }}>{s.body}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
